api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.getData), # This setting some end points
    path('add/',views.addItem)

]

home_app/urls.py
from django.contrib import admin
from django.urls import path
from home_app import views

app_name="home_app"

urlpatterns = [
   
    path("",views.home_app, name="home_app"),
    path("about/",views.about, name="about"),
  
]

localife_project/urls.py
from django.contrib import admin
from django.urls import path , include
from home_app import views
from django.conf import settings 
from django.conf.urls.static import static 
#from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home_app, name="home_app"),
    path("home/",include('home_app.urls')),
    path("user/",include('user_app.urls')),
    path("search/",include('search_app.urls')),    
    path("post/",include('post_app.urls')),
    path("book/",include('match_app.urls')),
    path("finished/",include('finished_app.urls')),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="schema_docs"), 
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT) 

search_app/urls.py
from django.contrib import admin
from django.urls import path , include
#from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from .views import index, SearchAPIView
from rest_framework import routers



from .views import search_app_result,experience_details,host_profile

app_name="search_app"


router = routers.DefaultRouter()
router.register(r'api',SearchAPIView, basename='api')


urlpatterns = [
    path("", index, name="search_index"),
    path(r'', include(router.urls)),
    path('experiences/search/results', search_app_result, name='experience_search_results'),
    path('experiences/search/results/details/<int:experience_id>/host', host_profile, name='host_profile'),
    path('experiences/search/results/details/<int:experience_id>/', experience_details, name='experience_details'),
    #path("schema/", SpectacularAPIView.as_view(), name="schema"),
    #path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="schema_docs"),
    
]

user_app/urls.py
from django.contrib import admin
from django.urls import path , include
from user_app import views
from django.contrib.auth import views as auth_views
from .views import UserProfileUpdate


app_name="user_app"

urlpatterns = [
    path("index/", views.index , name="index"),
    path("register/",views.register, name="register"),  
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("registration_success/", views.registration_success, name="success"),
    path('profile/update/<int:pk>/', views.UserProfileUpdate.as_view(), name='profile_update'),
    path("profile/",views.profile, name="user_profile"),
    
]

user_app/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, Group, Permission
from django.utils import timezone
#from django_google_maps import fields as map_fields


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="user_profile",
                                on_delete=models.CASCADE,null=True)
    # username = models.CharField(max_length=250, unique=True)
    # first_name = models.CharField(max_length=250)
    # last_name = models.CharField(max_length=250)
    # email = models.EmailField(("email address"), blank=False, unique=True)
    # password = models.CharField(max_length=200)
    # The user inherit from abstractUser which already has username, first name, last name, email and password
   
    location=models.CharField(max_length=200, blank=True)
    #address = map_fields.AddressField(max_length=200)
    #geolocation = map_fields.GeoLocationField(max_length=100)
    user_profile_image= models.ImageField(upload_to='user_app/profile_pics',blank=True, null=True)
    user_bio=models.TextField(default="Insert bio")
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        related_name='userprofile_set'  # Provide a unique related_name
    )
    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        related_name='userprofile_set'  # Provide a unique related_name
    )

    # additional customizations if needed

   
    def __str__(self):
        return f'{self.user.username}'


class TravelerProfile(models.Model):
    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    



    def __str__(self):
        return self.user_profile.user.username


class ExperienceTag(models.Model):
    tag_name=models.CharField(max_length=255)

    def __str__(self):
        return self.tag_name

class Region(models.Model):
    region_name=models.CharField(max_length=255)
    region_desc=models.TextField(max_length=1000)

class Experience(models.Model):
    host = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000,blank=False)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)    
    price = models.DecimalField(max_digits=12, decimal_places=2)
    experience_tags = models.ManyToManyField(ExperienceTag, null=True, blank=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE,default=1)  # Provide a default value hereRegion, on_delete=models.CASCADE)
    experience_image = models.ImageField(upload_to='experience_pics',blank=True, null=True)


    def __str__(self):
        return f'{self.title,self.id}'


class Booking(models.Model):
    traveler = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    
    

    def __str__(self):
        return f"{self.traveler.user.username} - {self.experience.title}"


class Review(models.Model):
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    listing = models.ForeignKey(Experience, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField()

    def __str__(self):
        return f"{self.author} - {self.listing.title}"
    

user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from user_app.models import UserProfile, TravelerProfile, ExperienceTag, Experience, Booking, Review


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'pattern': '[\w.@+-]+', 'title': 'Username should only contain letters, digits, and @/./+/-/_ characters.'})
    )
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model= User
        fields = ('username', 'first_name', 'last_name', 'email')



class UserProfileForm(forms.ModelForm):           
    
    class Meta:
        model = UserProfile
        fields = ('location', 'user_profile_image')
        labels = {
            
    
            'location': 'Location',
            'user_profile_image': 'Profile Image',
        }

class UserProfileLoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)
    
  

class TravelerProfileForm(forms.ModelForm):
    class Meta:
        model = TravelerProfile
        fields = []

class ExperienceTagForm(forms.ModelForm):
    class Meta:
        model = ExperienceTag
        fields = ['tag_name']

class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['title', 'description', 'price', 'experience_tags', 'experience_image']

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['traveler', 'experience', 'start_date', 'end_date']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['author', 'listing', 'rating', 'comment']

user_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from user_app.forms import UserProfileForm, RegistrationForm,UserProfileLoginForm
from user_app.models import UserProfile
from django.contrib.auth.models import User
from django.db import transaction
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from .models import UserProfile
from .serializers import UserProfileSerializer
from rest_framework import generics, status
from search_app.models import Booking
from user_app.models import Experience
from django.shortcuts import render,get_object_or_404
import time
from django.urls import reverse


class UserProfileUpdate(generics.RetrieveUpdateAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer
    #permission_classes = [IsAuthenticated]

"""
class UserProfileUpdateView(APIView):
    permission_classes = [IsAuthenticated]

    def put(self, request):
        user_profile = UserProfile.objects.get(user=request.user)
        serializer = UserProfileSerializer(user_profile, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        """

def index(request):
    return HttpResponse('index')

def profile(request):
    #Get the loggen-in user

    user=request.user
    booking_listing = Booking.objects.all()
    experience_listing=Experience.objects.all()
    if user.id==None or user.id-1<=0:
        return HttpResponse("Create profile")
    else:
        context={
            'user':user,
            'user_id':user.id,
            'booking_listing':booking_listing,
            'experience_listing':experience_listing
            
            
        }
        print(user.id)
        return render(request,'user_app/user_profile.html',context)

def extract_id(name):
    experience = Experience.objects.get(title=name)
    return experience.id



def registration_success(request):
   
    # Redirect to the login page
    
    return render(request,'registration/login.html')

def register(request):
    """This function handles the registration"""
    registered = False

    if request.method == 'POST':
        user_form = RegistrationForm(data=request.POST)

        if user_form.is_valid():
            # Save the user_form before checking for username existence
            

            username = user_form.cleaned_data['username']

            if User.objects.filter(username=username).exists():

                error_message = 'Username already exists. Please choose a different username.'
                user.delete()  # Delete the user if username exists
                return render(request, 'user_app/registration.html', {'user_form': user_form, 'error_message': error_message})
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            # new_user.set_password(user_form.cleaned_data['password'])
            # Create the UserProfile instance and assign the user_id field
            
            UserProfile.objects.create(user=user)
            messages.success(request, 'Registration successful!')

            registered = True
            return redirect('user_app:success')

    else:
        user_form = RegistrationForm()

    return render(request, 'user_app/registration.html', {
        'user_form': user_form,
        'registered': registered
    })

def user_login(request):
    if request.method == 'POST':
        form = UserProfileLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                if user.is_active:
                    login(request, user)
                    
                    return redirect('home_app')  # Replace 'home_app' with the correct URL name
                else:
                    return HttpResponse('ACCOUNT NOT ACTIVE')
            else:
                print('Someone tried to login and failed!')
                print("Username: {} and password {}".format(username, password))
                return HttpResponse("Invalid login details supplied!")
    else:
        form = UserProfileLoginForm()
    
    return render(request, 'user_app/login.html', {'form': form})

templates/user_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'user_app:index' %}">DJANGO</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                   
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_app:register' %}">Register</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
                    </li>
                
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>    
</body>
</html>

templates/user_app/login.html
{% extends 'user_app/base.html' %}

{% block body_block %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header">
                    <h1 class="text-center">Please Login</h1>
                </div>
                <div class="card-body">
                    <form action="{% url 'user_app:login' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" name="username" placeholder="Enter Username">
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user_app/registration.html
<!DOCTYPE html>

{% load static %} 

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>TraWell</title>
    <link rel="stylesheet" href="{% static 'main_style.css' %}"/>
    <link rel="stylesheet" href="{% static 'registration.css' %}"/>

    <!-- GOOGLE FONTS: -->

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Sketch&family=Londrina+Solid&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;1,400;1,500;1,700&family=Permanent+Marker&family=Sedgwick+Ave+Display&display=swap"
      rel="stylesheet"
    />

    <!-- FONTAWESOME ICONS: -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    /> 

  </head>
  
  <body>
    
    <div class="navbar-responsive">
      <div class="navbar">

        <div class="navbar-container-logo">
          <a href="{% url 'home_app' %}"><span class="logo">Tra<span class="well">Well</span> </span></a>
        </div>

        <div class="navbar-container-links">
          <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
          <a class="current-link" href="{% url 'user_app:register' %}">Registration</a>
          <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
          <a class="nav-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
          <a class="nav-link" href="{% url 'home_app:about' %}">About</a>
        </div>

      </div>
    </div>

<div class="content-placement">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <div class="main-content-container">

      <div class="card mt-5">
        <div class="card-body">
          <div class="text-center">
            {% if registered %}
            <h1 class="mb-4">Thank you for registering!</h1>
            {% else %}

            <h1 class="mb-3">Register Here!</h1>
            <div class="register-CTA">
            <h2 class="mb-4">Fill out the form to create your account!</h2>
            </div>
            {% endif %}
           <!--text center-->
          
          <form enctype="multipart/form-data" method="post" class="row g-3">
            {% csrf_token %}
            <div class="col-12">
              {{ user_form.as_p }}
            </div>
            {% if error_message %}
            <div class="col-12">
              <p class="text-danger">{{ error_message }}</p>
            </div>
            {% endif %}
            <!--<div class="col-12 text-center">-->
              <button type="submit" class="button1">Register</button>
            <!--</div>-->
          </form>
         </div> <!--text center-->
        </div>
        {% if not registered %}
        <div class="card-footer">
          <h2>Already have an account?<h2> <a class="button1" href="{% url 'user_app:login' %}">Log in</a>
        </div>
        {% endif %}
      </div>

    </div>

    </div>
  </div>
</div>
  </body>
</html>

templates/user_app/registration_success.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

    
</body>
</html>

templates/user_app/user_profile.html
<!DOCTYPE html>
{% load custom_filters %}
{% load static%}
<html>
<head>
  <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TraWell - search app</title>
    <link rel="stylesheet" href="{% static 'main_style.css' %}" />
    <link rel="stylesheet" href="{% static 'user_profile.css' %}" />
    <!-- GOOGLE FONTS: -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Sketch&family=Londrina+Solid&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;1,400;1,500;1,700&family=Permanent+Marker&family=Sedgwick+Ave+Display&display=swap"
      rel="stylesheet"
    />
    <!-- FONTAWESOME ICONS: -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>

</head>
<body>
  <div class="navbar-responsive">
    <div class="navbar">
      <div class="navbar-container-logo">
        <a href="{% url 'home_app'%}"><span class="logo">Tra<span class="well">Well</span> </span></a>
      </div>
      
      <div class="navbar-container-links">
        <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
        <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
        <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
        <a class="current-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
        <a class="nav-link" href="{% url 'home_app:about' %}">About</a>
      </div>
    </div>
  </div>
   
  </div>
  {% if user.is_authenticated %}
  <div class="content-placement">
      <div class="main-content-container">
        <div class="edit-profile"><a href="{% url 'user_app:profile_update' pk=user_id %}">Edit your info</a></div>
        <div class="profile-image-container">
          {% if user.user_profile.user_profile_image.url != null %}
          <img class="profile-picture-file" src="{{user.user_profile.user_profile_image.url}}" alt="User pic">
          {% else%}
          <img class="profile-picture-file" src="https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj.jpg" alt="">
          {% endif %}
        </div>
        <div class="profile-name">{{user.username}}</div>

      
      <div class="p1"><span class="bio">Bio:</span> <br>
        {{user.user_profile.user_bio}}
      </div>
        <div class="booked-experience-list">
          <img class="rocket" src="{% static 'rocket.png' %}" alt=""><b class="experience-list-head">Your upcoming experiences</b><br>
           {% for i in booking_listing %}
              {% if i.traveler  == user.username %}
              
              <p><b>Experience title:</b>
                <a href="{% url 'search_app:experience_details' experience_id=i.experience_name|extract_id %}">
                    {{ i.experience_name }}
                </a>  <b>, Host name:</b> {{i.host}}
            </p>
           
              {% endif %}
            {% endfor %}
          <img class="calendar" src="{% static 'calendar.png' %}" alt=""><b class="experience-list-head">Your hosting experiences</b>
          {% for i in booking_listing %}
              {% if i.host  == user.username %}
                <p><b>Experience title:</b>
                  
                  {{i.experience_name}}  <b>, Traveler's name:</b> {{i.traveler}} </p>
                  
              {% endif %}
            {% endfor %}
        </div>
      </div>
  </div> 
   
  {% else %}
  <h1>Please create an account to view your profile</h1>
  {% endif %}
</body>
</html>

templates/user_app/user_profile_old.html
{% load static%}
<!DOCTYPE html>
{% load custom_filters %}
<html>
<head>
  <title>TraWell - {% block title %}{% endblock %}</title>
  <style>
    /* Add your custom styles here */
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: #fdceaf;
    }
    .navbar {
      background-color: #2a6560;
      color: #fff;
      padding: 10px;
    }
    .navbar a {
      color: #fff;
      text-decoration: none;
      margin-right: 10px;
    }
    .navbar a:hover {
      color: #fff;
      text-decoration: underline;
    }
    .logo {
      color: #a94c77;
      font-size: 30px;
      margin-right: 10px;
    }
    .well {
      color: #fdceaf;
      font-size: 24px;
    }
    .content {
      padding: 20px;
      background-color: #fff;
      margin: 20px;
      display: flex;
      /**background-image: url("https://wallpaperswide.com/download/light_background-wallpaper-1920x1080.jpg");
      background-size: cover; **/
    }
    /* Profile Section Styles */
    .profile {
      display: flex;
      align-items: flex-start;
      
    }
    .profile-image {
      width: 300px;
      height: 300px;
      border-radius: 50%;
      background-color: #a94c77;
      margin-right: 20px;
    }

    .profile-picture-file{
      width: 300px;
      height: 300px;
       
      border-radius: 50%;
      border:6px solid #a94c77;
      margin-right: 20px;
    }
    .profile-name {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 35px;
      margin-top: 30px;
    }
    .profile-biography {
      font-size: 18px;
      line-height: 1.5;
      margin-left:40px;
      margin-top:100px
    }

    .bio{
        font-size: 18px;
        font-weight:bold;

    }

    .rocket{
      width: 40px;
      margin-top: 30px;
    }

    .calendar{
      width: 40px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="navbar">
    <a href="{% url 'home_app'%}"><span class="logo">Tra<span class="well">Well</span> </span></a>
    <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
    <a class="nav-link" href="{% url 'home_app' %}">Logout</a> <!--Needs to be updated-->

    <a href="#">About</a>
  </div>
  {% if user.is_authenticated %}
  <div class="content">
    <div class="profile">
      <div>
        <div class="edit-profile"><a href="{% url 'user_app:profile_update' pk=user_id %}">Edit your info</a></div>
        <div class="profile-name">{{user.username}}</div>
        <div class="profile-image">
          {% if user.user_profile.user_profile_image.url != null %}
          <img class="profile-picture-file" src="{{user.user_profile.user_profile_image.url}}" alt="User pic"></div>
          {% else%}
          <img class="profile-picture-file" src="https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj.jpg" alt="">
          {% endif %}
      </div>
      <div class="profile-biography"><span class="bio">Bio:</span> <br>
        {{user.user_profile.user_bio}}
        <div class="booked-experience-list">
          <img class="rocket" src="{% static 'rocket.png' %}" alt=""><b>Your upcoming experiences</b><br>
           {% for i in booking_listing %}
              {% if i.traveler  == user.username %}
              
              <p><b>Experience title:</b>
                <a href="{% url 'search_app:experience_details' experience_id=i.experience_name|extract_id %}">
                    {{ i.experience_name }}
                </a>  <b>, Host name:</b> {{i.host}}
            </p>
           
              {% endif %}
            {% endfor %}
          <img class="calendar" src="{% static 'calendar.png' %}" alt=""><b>Your hosting experiences</b>
          {% for i in booking_listing %}
              {% if i.host  == user.username %}
                <p><b>Experience title:</b>
                  
                  {{i.experience_name}}  <b>, Traveler's name:</b> {{i.traveler}} </p>
                  
              {% endif %}
            {% endfor %}
        </div>
      </div>
   
    </div>
  </div>
  {% else %}
  <h1>Please create an account to view your profile</h1>
  {% endif %}
</body>
</html>