api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.getData), # This setting some end points
    path('add/',views.addItem)

]

finished_app/urls.py
from django.contrib import admin
from django.urls import path , include
from finished_app import views

app_name="finished_app"
urlpatterns = [
    path("",views.finished_app, name="finished_app"),
    path("reviews/create/<int:experience_id>/", views.create_review, name='create_review' )
]

home_app/urls.py
from django.contrib import admin
from django.urls import path
from home_app import views

app_name="home_app"

urlpatterns = [
   
    path("",views.home_app, name="home_app"),
    path("about/",views.about, name="about"),
  
]

localife_project/urls.py
from django.contrib import admin
from django.urls import path , include
from home_app import views
from django.conf import settings 
from django.conf.urls.static import static 
#from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home_app, name="home_app"),
    path("home/",include('home_app.urls')),
    path("user/",include('user_app.urls')),
    path("search/",include('search_app.urls')),    
    path("post/",include('post_app.urls')),
    path("book/",include('match_app.urls')),
    path("finished/",include('finished_app.urls')),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="schema_docs"), 
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT) 

search_app/urls.py
from django.contrib import admin
from django.urls import path , include
#from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from .views import index, SearchAPIView
from rest_framework import routers



from .views import search_app_result,experience_details,host_profile

app_name="search_app"


router = routers.DefaultRouter()
router.register(r'api',SearchAPIView, basename='api')


urlpatterns = [
    path("", index, name="search_index"),
    path(r'', include(router.urls)),
    path('experiences/search/results', search_app_result, name='experience_search_results'),
    path('experiences/search/results/details/<int:experience_id>/host', host_profile, name='host_profile'),
    path('experiences/search/results/details/<int:experience_id>/', experience_details, name='experience_details'),
    #path("schema/", SpectacularAPIView.as_view(), name="schema"),
    #path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="schema_docs"),
    
]

user_app/urls.py
from django.contrib import admin
from django.urls import path , include
from user_app import views
from django.contrib.auth import views as auth_views
from .views import UserProfileUpdate


app_name="user_app"

urlpatterns = [
    path("index/", views.index , name="index"),
    path("register/",views.register, name="register"),  
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("registration_success/", views.registration_success, name="success"),
    path('profile/update/<int:pk>/', views.UserProfileUpdate.as_view(), name='profile_update'),
    path("profile/",views.profile, name="user_profile"),
    
]

search_app/models.py
from django.db import models

# Create your models here.


from django.views.generic import ListView
from django.db.models import Q
from user_app.models import Experience
from user_app.models import UserProfile,Experience

class Booking(models.Model):
    
    traveler=models.CharField(max_length=50)
    host=models.CharField(max_length=50)
    experience_name=models.CharField(max_length=200)
    """
    traveler=models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    host=models.ForeignKey(UserProfile, on_delete=models.CASCADE ,related_name='host_bookings')
    experience_name=models.ForeignKey(Experience,on_delete=models.CASCADE, related_name='bookings')
    """
    
    def __str__(self):
        return f' traveler: {self.traveler} , host: {self.host} , experience: {self.experience_name}'


class ExperienceSearchView(ListView):
    model = Experience
    template_name = 'experience_search.html'
    context_object_name = 'experiences'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()

        regions = self.request.GET.getlist('regions')
        tags = self.request.GET.getlist('tags')

        # Filter by regions
        if regions:
            queryset = queryset.filter(host__region__in=regions)

        # Filter by tags
        if tags:
            queryset = queryset.filter(experience_tags__in=tags)

        return queryset

search_app/forms.py
from django import forms

    

search_app/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.
from user_app.models import Experience,Review
from .filters import ExperienceFilter, SecondFilter, APIFilter
from .serializers import ExperienceSerializer, APISerializer

from django.views.generic import ListView
from django.db.models import Q
from .models import Booking
from django.http import HttpResponse




def search_app_result(request):
    return render(request,'search_app/experience_search_results.html')

def experience_details(request,experience_id):
    """
    OLD VERSION (WORKING)
    
    # Fetch the experience object or handle the case when it doesn't exist
    experience = get_object_or_404(Experience, id=experience_id)

    
    booking = Booking(
            traveler=request.user.user_profile,
            host=experience.host,
            experience_name=experience.title,
        )

    context = {
        'experience': experience,
        'experience_id':experience_id,
        'booking': booking,  # Pass the booking variable to the template

    }
    return render(request, 'search_app/experience_details.html', context)
"""

    
    if request.user.is_anonymous:
         return HttpResponse("You need to create an account in order to book the experience")
    else:
        # Fetch the experience object or handle the case when it doesn't exist
        experience = get_object_or_404(Experience, id=experience_id)
        review_list=Review.objects.all()

        if request.method == "POST":
            # Get data from the form submission
            traveler_post= request.POST.get("traveler")
            host_post= request.POST.get("host")
            experience_name = request.POST.get("experience_name")


            #If a booking already exists, redirect to other template
            booking = Booking(
                traveler=traveler_post,
                host=host_post,
                experience_name=experience_name,
                )

                
            existing_booking=Booking.objects.filter(traveler=request.user.user_profile,host=experience.host,experience_name=experience.title)
            if existing_booking:
                return HttpResponse("Sorry. You have already booked this experience")
            else:  
                    
                    
                booking.save()
                # Redirect to a success page or display a success message
                return HttpResponse("Booking successful!")
        else:
            context = {
                    'experience': experience,
                    'experience_id': experience_id,
                    'review_list':review_list,
                    
                }
            return render(request, 'search_app/experience_details.html', context)
        



    
def host_profile(request,experience_id):
    # Fetch the experience object or handle the case when it doesn't exist
    experience = get_object_or_404(Experience, id=experience_id)
    all_experiences = Experience.objects.all()

    context = {
        'experience': experience,
        'experience_id':experience_id,
        'all_experiences': all_experiences,
    }
    return render(request, 'search_app/host_profile.html', context)


''' KAI'S PART'''

def index(request):
    filter1 = ExperienceFilter(request.GET, queryset=Experience.objects.all())
    queryset = filter1.qs

    filter2 = SecondFilter(request.GET, queryset=queryset)
    #queryset2 = filter2.qs
    
    user=request.user
    if user.id==None or user.id-1<=0:
         user.id=1
         context = {
                'filter1': filter1,
                'filter2': filter2,
                'user_id':user.id-1
            }
         return render(request, 'search_app/search_app.html', context)
    else:
         context = {
                'filter1': filter1,
                'filter2': filter2,
                'user_id':user.id-1
            }
         return render(request, 'search_app/search_app.html', context)


    
"""
def granular(request, f):
    f2 = SecondFilter(request.GET, queryset=f)

    return render(request, 'search_app/granular_search.html', {"filter2": f2})
"""

from rest_framework import viewsets
from rest_framework.response import Response
from django_filters import rest_framework as drfilters

class SearchAPIView(viewsets.ModelViewSet):
        queryset = Experience.objects.all().order_by('region')
        serializer_class = APISerializer
        lookup_field = 'region'
        #filter_backends =(drfilters.DjangoFilterBackend, )
        #filterset_class = APIFilter
        #filterset_fields = ['price', 'start_date', 'end_date', 'region__region_name', 'host__username', 'experience_tags__tag_name']
        #filter_instance = APIFilter(request.query_params, queryset=queryset)
        #queryset = filter_instance.qs

        #serializer = ExperienceSerializer(queryset, many=True)

        def filter_queryset(self, queryset):
              filter_backends = (drfilters.DjangoFilterBackend, )
              
              for backend in list(filter_backends):
                    queryset = backend().filter_queryset(self.request, queryset, view=self)
              return queryset
        filterset_class = APIFilter

templates/search_app/experience_details.html
<!DOCTYPE html>
{% load custom_filters %}
{% load static%}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TraWell - search app</title>
    <link rel="stylesheet" href="{% static 'main_style.css' %}" />
    <link rel="stylesheet" href="{% static 'experience_details.css' %}" />
    <!-- GOOGLE FONTS: -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Sketch&family=Londrina+Solid&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;1,400;1,500;1,700&family=Permanent+Marker&family=Sedgwick+Ave+Display&display=swap"
      rel="stylesheet"
    />
    <!-- FONTAWESOME ICONS: -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>
   
  </head>
  <body>
    <div class="navbar-responsive">
      <div class="navbar">
        <div class="navbar-container-logo">
        <a href="{% url 'home_app'%}"><span class="logo">Tra<span class="well">Well</span> </span></a>
        </div>
        <div class="navbar-container-links">
          <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
          <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
          <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
          <a class="nav-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
          <a class="nav-link" href="{% url 'home_app:about' %}">About</a>
        </div>
      </div>
    </div>

    
      
          <div class="experience-container">
          <div class="experience-title">{{experience.title}}</div>
          <div class="experience-picture">
            <img
              class="experience-picture-file"
              src="{{experience.experience_image.url}}"
              alt="experience image"
            />
          </div>
        
        <div class="experience-description">
          <br />
          <h2 class="experience-description-header">Description</h2>
          {{experience.description}}
          <h2 class="experience-price-header">Price</h2>
          <p class="price">{{experience.price}}</p>
        </div>
        
          
          <button id="book-button" class="book-button">Book now</button>
        
      <!-- Hidden form for booking -->
     <form id="booking-form" method="post" action="{% url 'search_app:experience_details' experience_id=experience_id %}">
        {% csrf_token %}
        <input type="hidden" name="traveler" value="{{ request.user.user_profile }}">
        <input type="hidden" name="host" value="{{ experience.host }}">
        <input type="hidden" name="experience_name" value="{{ experience.title }}">
      </form>

      <div class="host-section">
        <h2 class="host-header">Your Host</h2>
        {% if experience.host.user_profile_image.url != null %}
        <p><a href="{% url 'search_app:host_profile' experience_id=experience_id %}"><img
          class="host-picture"
          src="{{experience.host.user_profile_image.url}}"
          alt="host image"
        /></a><span class="host-name">{{experience.host}}</span></p> 
        {% else%}
        <p><a href="{% url 'search_app:host_profile' experience_id=experience_id %}"><img
          class="host-picture"
          src="https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj.jpg"
          alt="host image"
        /></a> <span class="host-name">{{experience.host}}</span></p>
        {% endif %}
        
        
      <p><span class="host-location">Location: </span>{{experience.host.location}}</p>
      <p><span class="host-email">Email: </span>{{experience.host}}@gmail.com</p>
      </div> 
          
      <h2 class="reviews-header">Reviews</h2>
      <div class="review-container">
        <div class="review-box">
         {% for i in review_list %}
          {% if i.listing.id == experience_id %}
          
            {% if i.author.user_profile_image.url != null %}
              <p ><img class="review-host-pic" src="{{i.author.user_profile_image.url}}" alt="host pic"><span class="author-name"> {{i.author}}</span> </p>
              {% else%}
              <p><img class="review-host-pic" src="https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj.jpg"  alt="host pic">{{i.author}} </p>
            {% endif %}
            <p><b>Rating: {{ i.rating|get_star_emoji }}</b></p>
            <p class="review-comment"> {{i.comment}}</p>
          </div>
          {% endif %}
        {% endfor %}
      </div>
        <h4>Write your own review and help other travelers like you!</h4>
        <a class="review-button" href="{%url 'finished_app:create_review' experience_id=experience_id%}"> Write review</a>
          
      

        
      

    <!-- JavaScript script -->
  <script>
    document.getElementById("book-button").addEventListener("click", function () {
      // Submit the booking form
      const bookingForm = document.getElementById("booking-form");
      bookingForm.submit();
    });
  </script>
  </body>
</html>

templates/search_app/experience_details_old.html
<!DOCTYPE html>
{% load custom_filters %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      /* Add your custom styles here */
      body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
        background-color: #fdceaf;
      }
      .navbar {
        background-color: #2a6560;
        color: #fff;
        padding: 10px;
      }
      .navbar a {
        color: #fff;
        text-decoration: none;
        margin-right: 10px;
      }
      .navbar a:hover {
        color: #fff;
        text-decoration: underline;
      }
      .logo {
        color: #a94c77;
        font-size: 30px;
        margin-right: 10px;
      }
      .well {
        color: #fdceaf;
        font-size: 24px;
      }
      .content {
        padding: 20px;
        background-color: #fff;
        margin: 20px;
        display: flex;
      }
      /* Profile Section Styles */
      .experience {
        display: flex;
        align-items: flex-start;
      }
      .experience-picture {
        width: 700px;
        height: 500px;
        /**border-radius: 50%;**/
        background-color: #a94c77;
        margin-right: 20px;
      }

      .experience-picture-file {
        width: 700px;
        height: 500px;

        /**border-radius: 50%;**/
        border: 6px solid #a94c77;
        margin-right: 20px;
      }
      .experience-title {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 35px;
        margin-top: 30px;
      }
      .experience-description {
        font-size: 18px;
        line-height: 1.5;
        margin-left: 30px;
        margin-top: 100px;
      }
      .book-button {
        display: inline-block;
        width: fit-content;
        margin-top: 100px;
        margin-left: 0px;
        padding: 10px 20px;
        background-color: #a94c77;
        color: #fff;
        font-size: 30px;
        text-decoration: none;
        border-radius: 10px;
        height: auto;
      }
      .book-button:hover {
        background-color: #fdceaf; /* Update with your desired hover color */
      }

      .review_container{
        background-color: rgba(17, 80, 208, 0.171);
        border-radius: 15px;

      }

      .review_container p{
        margin-left: 20px;
        padding-top: 10px;

      }

      .review_comment{
        background-color: rgb(254, 254, 255);
        border-radius: 10px;
        margin-bottom: 30px;
        margin-right: 10px;
        padding-left: 5px;
        padding-bottom: 5px;

      }

      .review-host-pic{
        width:35px;
        height:35px;
        border-radius: 50px;
      }

      .review-button {
        display: inline-block;
        width: fit-content;
        margin-top: 20px;
        margin-left: 0px;
        padding: 10px 20px;
        background-color: #a94c77;
        color: #fff;
        font-size: 30px;
        text-decoration: none;
        border-radius: 10px;
        height: auto;
      }
      .review-button:hover {
        background-color: #fdceaf; /* Update with your desired hover color */
      }

      .host-section {
        margin-left: 700px;
      }

      .host-section h2 {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
      }

      .host-picture {
        width: 200px;
        height: 200px;
        border-radius: 50%;
        margin-top: 20px;
      }
    </style>
  </head>
  <body>
    <div class="navbar">
      <a href="{% url 'home_app' %}"
        ><span class="logo">Tra<span class="well">Well</span> </span></a
      >
      <!--<a class="nav-link" href="{% url 'search_app:experience_search_results' %}">Search</a>-->
      <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
      <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
      <a href="#">About</a>
    </div>

    <div class="content">
      <div class="experience">
        <div>
          <div class="experience-title">{{experience.title}}</div>
          <div class="experience_picture">
            <img
              class="experience-picture-file"
              src="{{experience.experience_image.url}}"
              alt="experience image"
            />
          </div>
        </div>
        <div class="experience-description">
          <br />
          <h2>Description</h2>
          {{experience.description}}
          <h2>Price</h2>
          <p>{{experience.price}}</p>
          <!--<a href="" class="book-button" action={{booking}} >Book now</a>-->
          <button id="book-button" class="book-button">Book now</button>

      <!-- Hidden form for booking -->
      <form id="booking-form" method="post" action="{% url 'search_app:experience_details' experience_id=experience_id %}">
        {% csrf_token %}
        <input type="hidden" name="traveler" value="{{ request.user.user_profile }}">
        <input type="hidden" name="host" value="{{ experience.host }}">
        <input type="hidden" name="experience_name" value="{{ experience.title }}">
      </form>
          
      <h2>Reviews</h2>

         {% for i in review_list %}
          {% if i.listing.id == experience_id %}
          <div class="review_container">
            {% if i.author.user_profile_image.url != null %}
              <p><b>Left by:</b>  {{i.author}} <img class="review-host-pic" src="{{i.author.user_profile_image.url}}" alt="host pic"></p>
              {% else%}
              <p><b>Left by:</b>  {{i.author}} <img class="review-host-pic" src="https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj.jpg"  alt="host pic"></p>
            {% endif %}
            <p><b>Rating: {{ i.rating|get_star_emoji }}</b></p>
            <p class="review_comment"><b>Comment:</b> {{i.comment}}</p>
          </div>
          {% endif %}
        {% endfor %}
        <h2>Write your own review and help other travelers like you!</h2>
        <a class="review-button" href="{%url 'finished_app:create_review' experience_id=experience_id%}"> Write review</a>
          
        </div>

        <div class="host-section">
          <h2>Your Host</h2>
          {% if experience.host.user_profile_image.url != null %}
          <a href="{% url 'search_app:host_profile' experience_id=experience_id %}"><img
            class="host-picture"
            src="{{experience.host.user_profile_image.url}}"
            alt="host image"
          /></a>
          {% else%}
          <a href="{% url 'search_app:host_profile' experience_id=experience_id %}"><img
            class="host-picture"
            src="https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj.jpg"
            alt="host image"
          /></a>
          {% endif %}
          
          <h2>Name</h2>
          {{experience.host}}
          <h2>Location</h2>
            {{experience.host.location}}
        </div>
      </div>
    </div>

    <!-- JavaScript script -->
  <script>
    document.getElementById("book-button").addEventListener("click", function () {
      // Submit the booking form
      const bookingForm = document.getElementById("booking-form");
      bookingForm.submit();
    });
  </script>
  </body>
</html>

templates/search_app/host_profile.html
<!DOCTYPE html>
{% load custom_filters %}
{% load static%}
<html>
<head>
  <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TraWell - search app</title>
    <link rel="stylesheet" href="{% static 'main_style.css' %}" />
    <link rel="stylesheet" href="{% static 'host_profile.css' %}" />
    <!-- GOOGLE FONTS: -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Sketch&family=Londrina+Solid&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;1,400;1,500;1,700&family=Permanent+Marker&family=Sedgwick+Ave+Display&display=swap"
      rel="stylesheet"
    />
    <!-- FONTAWESOME ICONS: -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>

</head>
 
<body>
  <div class="navbar-responsive">
    <div class="navbar">
      <div class="navbar-container-logo">
      <a href="{% url 'home_app'%}"><span class="logo">Tra<span class="well">Well</span> </span></a>
      </div>
      <div class="navbar-container-links">
        <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
        <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
        <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
        <a class="nav-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
        <a class="current-link" href="#">Host Profile</a>
        <a class="nav-link" href="{% url 'home_app:about' %}">About</a>
      </div>
    </div>
  </div>
 
  
  <div class="content-placement">
      <div class="main-content-container">
      
        <div class="profile-image-container">
          {% if experience.host.user_profile_image.url != null %}
          <img class="profile-picture-file" src="{{experience.host.user_profile_image.url}}" alt="host pic">
          {% else%}
          <img class="profile-picture-file" src="https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj.jpg" alt="">
          {% endif %}
        </div>

        <div class="profile-name">{{experience.host}}</div>
          
      
        <div class="p1"><span class="bio">Bio:</span> <br>
          {{experience.host.user_bio}}
        </div>

        <div class="exp-results">
          <p class="experience-offered-heading">Experiences offered by this host</p>
          
          {% for i in all_experiences %}
            {% if i.host == experience.host %}

                <div class="exp">
                  <h2 class="exp_title">{{i.title }}</h2>
                  <img class="experience_image" src="{{i.experience_image.url}}" alt="">
                   <!--<p class="experience_description">{{ i.description }}</p> DO WE WANT THE DESCRIPTION IN PREVIEW? -->
                   <a class="button1" href="{% url 'search_app:experience_details' experience_id=i.id %}">View more</a>
                <!-- Add more fields as needed -->
                </div>

            {%endif%}
          {% endfor %}

        </div>
      </div>

  </div>

      
    
  
  
</body>
</html>

templates/search_app/search_app.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TraWell - search app</title>
    <link rel="stylesheet" href="{% static 'main_style.css' %}" />
    <link rel="stylesheet" href="{% static 'search_app.css' %}" />
    <!-- GOOGLE FONTS: -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Sketch&family=Londrina+Solid&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;1,400;1,500;1,700&family=Permanent+Marker&family=Sedgwick+Ave+Display&display=swap"
      rel="stylesheet"
    />
    <!-- FONTAWESOME ICONS: -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>

  <body>
    {% block content %}
    <div class="navbar-responsive">
      <div class="navbar">
        <div class="navbar-container-logo">
          <a href="{% url 'home_app' %}"
            ><span class="logo">Tra<span class="well">Well</span> </span></a
          >
        </div>
        <div class="navbar-container-links">
          <a class="current-link" href="{% url 'search_app:search_index' %}">Search</a>
          <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
          <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
          <a class="nav-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
          <a class="nav-link" href="{% url 'home_app:about' %}">About</a>
        </div>
      </div>
    </div>

    <div class="content-placement">

      <div class="main-content-container">

        <div>
          <h1 class="main-heading1">
            Find your <br /><span class="h1-tab">experience</span>
          </h1>
        </div>

        <div class="form-container">
          <h1>Customize your search</h1>
          <form method="get">
            {{ filter1.form.as_p }} {{ filter2.form.as_p }}
            <input type="submit" />

          </form>
        </div>

        <div class="exp-available-content">
          <h1>Experiences available:</h1>

          <div class="exp-results">
            {% for obj in filter2.qs %} {% if obj.host.id != user_id %}

            <div class="exp">
              <img
                src="{{obj.experience_image.url}}"
                alt="Experience Image"
                class="experience_image"
              />
              <h2 class="exp-title">{{obj.title}}</h2>
              <p class="exp-host"><b>Host:</b> {{ obj.host }}</p>
              <p class="exp-price">Price: {{obj.price}}</p>
              <a
                href="{% url 'search_app:experience_details' experience_id=obj.id %}"
                class="button1"
                >View details</a>
            </div> <!--exp-->
            {%endif%}
                {% endfor %}
          </div> <!--exp-results-->

        </div> <!--exp-available-content-->

      </div> <!--main-content-container-->

    </div> <!--content-placement-->

    {% endblock %}
  </body>
</html>