api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.getData), # This setting some end points
    path('add/',views.addItem)

]

home_app/urls.py
from django.contrib import admin
from django.urls import path
from home_app import views

app_name="home_app"

urlpatterns = [
   
    path("",views.home_app, name="home_app"),
    path("about/",views.about, name="about"),
  
]

localife_project/urls.py
from django.contrib import admin
from django.urls import path , include
from home_app import views
from django.conf import settings 
from django.conf.urls.static import static 
#from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home_app, name="home_app"),
    path("home/",include('home_app.urls')),
    path("user/",include('user_app.urls')),
    path("search/",include('search_app.urls')),    
    path("post/",include('post_app.urls')),
    path("book/",include('match_app.urls')),
    path("finished/",include('finished_app.urls')),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="schema_docs"), 
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT) 

post_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import ExperienceUpdate

app_name="post_app"

urlpatterns = [

    path('' , views.experience_list , name="post_list"),
    path('list/', views.experience_list, name='experience_list'),
    path('create/', views.create_experience, name='post_create'),
    path('test_view/', views.test_view, name='test_view'),
    path('detail/<int:id>/', views.experience_detail, name='post_detail'),
    path('api/v1/update/<int:pk>/', views.ExperienceUpdate.as_view(), name='post_update'),
]

search_app/urls.py
from django.contrib import admin
from django.urls import path , include
#from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from .views import index, SearchAPIView
from rest_framework import routers



from .views import search_app_result,experience_details,host_profile

app_name="search_app"


router = routers.DefaultRouter()
router.register(r'api',SearchAPIView, basename='api')


urlpatterns = [
    path("", index, name="search_index"),
    path(r'', include(router.urls)),
    path('experiences/search/results', search_app_result, name='experience_search_results'),
    path('experiences/search/results/details/<int:experience_id>/host', host_profile, name='host_profile'),
    path('experiences/search/results/details/<int:experience_id>/', experience_details, name='experience_details'),
    #path("schema/", SpectacularAPIView.as_view(), name="schema"),
    #path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="schema_docs"),
    
]

user_app/urls.py
from django.contrib import admin
from django.urls import path , include
from user_app import views
from django.contrib.auth import views as auth_views
from .views import UserProfileUpdate


app_name="user_app"

urlpatterns = [
    path("index/", views.index , name="index"),
    path("register/",views.register, name="register"),  
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("registration_success/", views.registration_success, name="success"),
    path('profile/update/<int:pk>/', views.UserProfileUpdate.as_view(), name='profile_update'),
    path("profile/",views.profile, name="user_profile"),
    
]

home_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.



def home_app(request):
    return render(request,'home_app/home_app.html')

def about(request):
    return render(request,'home_app/about.html')

templates/home_app/about.html
<!DOCTYPE html>

{% load static %}

<html>
  <head>
    <title>TraWell - {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'main_style.css' %}"/>
    <link rel="stylesheet" href="{% static 'about.css' %}"/>

    <!-- GOOGLE FONTS: -->

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Sketch&family=Londrina+Solid&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;1,400;1,500;1,700&family=Permanent+Marker&family=Sedgwick+Ave+Display&display=swap"
      rel="stylesheet"
    />

    <!-- FONTAWESOME ICONS: -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    /> 
    <!--<style>
      /* Add your custom styles here */
      body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
        /**background-image: url(https://images.unsplash.com/photo-1444464666168-49d633b86797?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1469&q=80)**/
        background-repeat: no-repeat;
        background-size: cover;
        transition: background-image 2s ease-in-out;
      }
      .navbar {
        background-color: #2a6560;
        color: #fff;
        padding: 10px;
      }
      .navbar a {
        color: #fff;
        text-decoration: none;
        margin-right: 10px;
      }
      .navbar a:hover {
        color: #fff;
        text-decoration: underline;
      }
      .logo {
        color: #a94c77;
        font-size: 30px;
        margin-right: 10px;
      }

      .well {
        color: #fdceaf;
        font-size: 24px;
      
      }
      .content-container{
        background-color: rgba(0, 0, 0, 0.558);
    /* Set the height to occupy the remaining viewport height after the navbar */
    height: calc(100vh - 50px); /* 50px is the height of the navbar, adjust as needed */
    overflow: auto; /* Add this to enable scrolling if content overflows */
      }
      .main-content {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100px;
        padding: 0 50px;
        box-sizing: border-box;
        margin-top: 200px;
      }

      .main-heading {
        font-size: 40px;
        color: #fff;
        text-align: right;
      }

      .home-p {
        margin-left: 50px;
        margin-bottom: 50px;
        padding-left: 800px;
        width: 800px;
        color: #fff;
        font-size: 25px;
      }
      .main-button {
        display: block;
        width: fit-content;
        margin-top: 10px;
        margin-left: 50px;
        padding: 10px 20px;
        background-color: #a94c77;
        color: #fff;
        font-size: 30px;
        text-decoration: none;
        border-radius: 10px;
      }
      .main-button:hover {
        background-color: #fdceaf; /* Update with your desired hover color */
      }
      /* Owl Carousel styles */
      .owl-carousel {
        margin-top: 30px;
      }
      .owl-carousel .owl-item {
        background: #fff;
        padding: 20px;
        border-radius: 5px;
        text-align: center;
      }
      .owl-carousel .owl-item p {
        margin-bottom: 10px;
        font-size: 18px;
        color: #444;
      }

    </style> -->
    
  </head>
  <body>
    <div class="navbar-responsive">
      <div class="navbar">
        <div class="navbar-container-logo">
         <a href="{% url 'home_app' %}"><span class="logo">Tra<span class="well">Well</span> </span></a>
        </div>
        
        <div class="navbar-container-links">
          <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
          <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
          <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
          <a class="nav-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
          <a class="current-link" href="{% url 'home_app:about' %}">About</a>
        </div>
      </div>
    </div>
  
  <div class="background-carousel">
    <div class="background-item"></div>
    <div class="background-item"></div>
  </div>

  <div class="content-placement">
    <div class="main-content-container">
      <div class="main-heading-container">
        <h1 class="main-heading1">We are<br><span class="h1-tab">TraWell</span></h1>
      </div>
      <p class="p1">
      

      Welcome to TraWell, a pioneering company that is committed to unlocking
      the hidden gems of uncharted destinations and providing a platform for
      authentic tourism experiences. Our passion lies in redefining travel,
      going beyond the beaten path, and fostering meaningful connections between
      travelers and the local communities they visit.
    </p>
    <p class="p1">
    <b class="about-heading">Our Mission</b><br>
    <br>
      At TraWell, we believe that every destination has a unique
      story to tell, and it's our mission to ensure that these untold narratives
      are accessible to all travelers. Our goal is to empower travelers to
      explore lesser-known locations, embrace diverse cultures, and immerse
      themselves in authentic experiences that leave lasting memories.
    </p>
      <p class="p1"> 
      <b class="about-heading">Discovering the Uncharted</b><br>
      <br> 
      We are on a constant quest to discover the
      unexplored corners of the world. Our team of avid explorers and local
      experts work hand in hand to identify extraordinary destinations that have
      been overlooked by conventional travel agencies. Whether it's a remote
      village nestled amidst breathtaking landscapes or a culturally rich urban
      enclave, TraWell curates exceptional travel experiences for the
      adventurous at heart. 
      </p>
      <p class="p1">
      <b class="about-heading">Promoting Authenticity</b><br>
      <br> 
      Authenticity is at the core
      of everything we do. We believe that genuine travel experiences come from
      connecting with the heart and soul of a place. To achieve this, TraWell
      collaborates closely with local communities and businesses. We actively
      support and engage with local artisans, craftsmen, and guides to ensure
      that our travelers can partake in authentic traditions and witness the
      beauty of local culture. 
    </p>
      <p class="p1">
      <b class="about-heading">Empowering Local Communities</b><br>
      <br> 
      We believe that tourism
      should be a force for good, benefiting the communities it touches. By
      collaborating with locals and involving them in our operations, we aim to
      create a positive socio-economic impact. We contribute to community
      projects, promote sustainable practices, and encourage responsible tourism
      that respects the environment and preserves the natural wonders of the
      destinations we explore.
    </p>
    </p>
</div>
  </div>

   

  
  </body>
</html>

templates/home_app/home_app.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TraWell</title>
    <link rel="stylesheet" href="{% static 'main_style.css' %}"/>
    <link rel="stylesheet" href="{% static 'home_app.css' %}"/>
    <!-- GOOGLE FONTS: -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Sketch&family=Londrina+Solid&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;1,400;1,500;1,700&family=Permanent+Marker&family=Sedgwick+Ave+Display&display=swap"
      rel="stylesheet"
    />
    <!-- FONTAWESOME ICONS: -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>
  <style>
  </style>
  <body>
    <div class="navbar-responsive">
      <div class="navbar">
        <div class="navbar-container-logo">
          <a href="{% url 'home_app' %}"><span class="logo">Tra<span class="well">Well</span> </span></a>
        </div>
        <div class="navbar-container-links">
          <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
          <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
          <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
          <a class="nav-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
          <a class="nav-link" href="{% url 'home_app:about' %}">About</a>
        </div>
      </div>
    </div>
    <div class="background-carousel">
      <div class="background-item"></div>
      <div class="background-item"></div>
    </div>
    <div class="content-placement">
      <div class="main-content-container">
        <div class="main-heading-container">
          <h1 class="main-heading1">Find your <br><span class="h1-tab">experience</span></h1>
        </div>
        <p class="p1">
          Embark on a journey of discovery and immerse yourself in the vibrant tapestry of local cultures.
          Click the button below to explore and book your first authentic local experience, creating
          memories that will last a lifetime.
        </p>
        <a class="button1" href="{% url 'search_app:search_index' %}">Explore</a>
        <p class="p2">
          Ready to share your culture with curious travelers?
          Craft a captivating experience filled with local charm and cherished traditions.
        </p>
        <a class="button1" href="{% url 'post_app:post_create' %}">Create</a>
        <div class="content">{% block content %}{% endblock %}</div>
      </div>
    </div>

    <script>
      window.addEventListener("load", function () {
        var images = [
          "media/background_pics/unsplash/yunchuan-luo-7emiteIwfuk-unsplash.jpg",
          "media/background_pics/unsplash/2-ignacio-correia-Q4AW5tWkd8Q-unsplash.jpg",
          "media/background_pics/unsplash/3-subtle-cinematics-O5Fr1BZ-aR4-unsplash.jpg",
          "media/background_pics/unsplash/4-ted-bryan-yu-5mezpWin6T8-unsplash.jpg",
          "media/background_pics/unsplash/Philippines/6-ramon-kagie-4EZKcKxOlRE-unsplash.jpg"
        ];
        var currentIndex = 0;
        var backgroundItems = document.querySelectorAll(".background-item");
  
        function changeBackgroundImage() {
          var nextIndex = (currentIndex + 1) % images.length;
          var currentImage = images[currentIndex];
          var nextImage = images[nextIndex];
  
          backgroundItems[0].style.backgroundImage = "url(" + currentImage + ")";
          backgroundItems[0].style.opacity = 1;
          backgroundItems[1].style.backgroundImage = "url(" + nextImage + ")";
          backgroundItems[1].style.opacity = 0;
  
          setTimeout(function () {
            backgroundItems[0].style.opacity = 0;
            backgroundItems[1].style.opacity = 1;
            currentIndex = nextIndex;
          }, 8000);
        }
  
        changeBackgroundImage();
        setInterval(changeBackgroundImage, 8000);
      });
    </script> 
  </body>
</html>

templates/home_app/home_app_old.html
<!--
<!DOCTYPE html>
<html>
  <head>
    <title>TraWell - {% block title %}{% endblock %}</title>
    <style>
      /* Add your custom styles here */
      body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
        /**background-image: url(https://images.unsplash.com/photo-1444464666168-49d633b86797?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1469&q=80)**/;
        background-repeat: no-repeat;
        background-size: cover;
        transition: background-image 2.0s ease-in-out;
      }
      .navbar {
        background-color: #2a6560;
        color: #fff;
        padding: 10px;
      }
      .navbar a {
        color: #fff;
        text-decoration: none;
        margin-right: 10px;
      }
      .navbar a:hover {
        color: #fff;
        text-decoration: underline;
      }
      .logo {
        color: #a94c77;
        font-size: 30px;
        margin-right: 10px;
      }

      .well {
        color: #fdceaf;
        font-size: 24px;
      }
      .main-content {
        display: flex;
        justify-content: flex-start;
        align-items: center;
        height: 100px;
        padding: 0 50px;
        box-sizing: border-box;
        margin-top: 200px;
        
      }

      .main-heading {
        font-size: 40px;
        color: #fff;
        text-align: right;
      }

      .home-p {
        margin-left: 50px;
        margin-bottom: 50px;
        width: 400px;
        color: #fff;
        font-size: 25px;
      }
      .main-button {
        display: block;
        width: fit-content;
        margin-top: 10px;
        margin-left: 50px;
        padding: 10px 20px;
        background-color: #a94c77;
        color: #fff;
        font-size: 30px;
        text-decoration: none;
        border-radius: 10px;
      }
      .main-button:hover {
        background-color: #fdceaf; /* Update with your desired hover color */
      }
    /* Owl Carousel styles */
    .owl-carousel {
        margin-top: 30px;
      }
      .owl-carousel .owl-item {
        background: #fff;
        padding: 20px;
        border-radius: 5px;
        text-align: center;
      }
      .owl-carousel .owl-item p {
        margin-bottom: 10px;
        font-size: 18px;
        color: #444;
      }
      
    </style>
        <script>
            window.addEventListener("load", function () {
              var images = [
                "https://images.unsplash.com/photo-1444464666168-49d633b86797?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1469&q=80",
                "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1476&q=80",
                "https://images.unsplash.com/photo-1476820865390-c52aeebb9891?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
              ];
              var currentIndex = 0;
              var body = document.getElementsByTagName("body")[0];
      
              function changeBackgroundImage() {
                body.style.backgroundImage = "url(" + images[currentIndex] + ")";
                currentIndex = (currentIndex + 1) % images.length;
              }
      
              // Change background image every 5 seconds
              setInterval(changeBackgroundImage, 5000);
            });
          </script>
  </head>
  <body>
    <div class="navbar">
      <a href="#"><span class="logo">Tra<span class="well">Well</span> </span></a>
      <a class="nav-link" href="{% url 'search_app:search_index' %}">Search</a>
      <a class="nav-link" href="{% url 'user_app:register' %}">Registration</a>
      <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
      <a class="nav-link" href="{% url 'user_app:user_profile' %}">My Profile</a>
      <a class="nav-link" href="{% url 'home_app:about' %}">About</a>

      
      
    </div>

    <div class="main-content">
      <h1 class="main-heading">Find your experience</h1>
    </div>
    <p class="home-p">
        Embark on a journey of discovery and immerse yourself in the vibrant tapestry of local cultures. Click the button below to explore and book your first authentic local experience, creating memories that will last a lifetime.</p>
    </p>
    <a class="main-button" href="{% url 'search_app:search_index' %}">Explore</a>

    <div class="content">{% block content %} {% endblock %}</div>
  </body>
</html>

-->